feat(payments): PAYPAL-847 Add PPCP to README
bigcommerce/checkout-sdk-js pull request #1017
Opened 2020-11-18 10:39 UTC by helga1507

## What?
Add PPCP to README

## Why?
For the checkout-sdk readme file, we need to mention that Paypal Commerce has specific options for the initialization (as it is mentioned for Amazon)

## Testing / Proof
<img width="1278" alt="Screenshot 2020-11-18 at 12 38 30" src="https://user-images.githubusercontent.com/32959076/99519783-f827ea80-299a-11eb-9a85-0aedae54e5f1.png">

@bigcommerce/checkout @bigcommerce/payments

2020-11-23 23:17 UTC, davidchin commented on README.md
> +        submitForm: () => {
Maybe explain what these callbacks are meant to do `submitForm`, `onValidate` and `onRenderButton`?

2020-11-24 07:46 UTC, BC-ACherednichenko requested changes

2020-11-24 07:46 UTC, BC-ACherednichenko commented on README.md
> +            service.submitOrder({ methodId: 'paypalcommerce', });
@helga1507 payload should be 
```js
    payment: {
        methodId: 'paypalcommerce',
    },
```

2020-11-24 07:55 UTC, BC-ACherednichenko commented on README.md
> +            service.submitOrder({ methodId: 'paypalcommerce', });
Can you update it here as well 
https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/paypalcommercepaymentinitializeoptions.md

2020-11-24 17:57 UTC, BC-ACherednichenko commented
closing in favor of https://github.com/bigcommerce/checkout-sdk-js/pull/1022

2020-11-24 17:57 UTC, closed without merging