fix(payment): INT-3611 Refresh the state in Braintree
bigcommerce/checkout-sdk-js pull request #1061
Opened 2021-01-26 19:05 UTC by roberbnd

## What?
...

## Why?
...

## Testing / Proof
...

@bigcommerce/checkout @bigcommerce/payments

2021-01-26 20:16 UTC, mauricio-sg requested changes
I suggest some adjustments to keep consistency with other strategies.

2021-01-27 20:25 UTC, roberbnd commented
@mauricio-sg  could you review, please?

2021-01-30 01:46 UTC, mauricio-sg approved these changes
LGTM 👍

2021-01-30 01:46 UTC, mauricio-sg commented on src/payment/strategies/braintree/braintree-paypal-payment-strategy.spec.ts
> +        it('does submit paypal if a nonce is present', async () => {
Why you changed the name? 🤔

2021-02-10 00:28 UTC, mmartinezintersys commented
💚 TESTED

QA Details:

 - Verify the shopper can do a second payment attempt after a declined transaction with PayPal
 - Verify the shopper can do a successfull payment with PayPal
 - Verify the shopper can do a successfull payment with a credit cards

2021-02-10 23:20 UTC, capsula4 commented on src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
> +        } else {
minor, if you are returning inside `if`, you don't need `else`. It just makes it easier to read/follow

2021-02-10 23:21 UTC, capsula4 approved these changes

2021-02-11 23:21 UTC, merged