fix(payment): INT-3896 It changes the referred returned value with ch…
bigcommerce/checkout-sdk-js pull request #1075
Opened 2021-02-18 15:57 UTC by roberbnd

…eckoutId

## What?  [](https://jira.bigcommerce.com/browse/INT-3896)

## Why?

## Testing / Proof

@bigcommerce/checkout @bigcommerce/payments @bigcommerce/apex-integrations

2021-02-18 22:38 UTC, capsula4 commented on src/payment/strategies/zip/zip-payment-strategy.ts
> +                        checkoutId) {
closing brace should be aligned with opening brace

2021-02-19 22:31 UTC, mauricio-sg approved these changes

2021-02-23 13:56 UTC, josesonora requested changes

2021-02-23 13:56 UTC, josesonora commented on src/payment/strategies/zip/zip-payment-strategy.ts
> +                        if (this._paymentMethod?.initializationData?.experimentZipDeferredFlow) {
Take a glance at this comment https://github.com/bigcommerce/bigcommerce/pull/39599#discussion_r581046249

2021-02-23 19:51 UTC, josesonora approved these changes

2021-02-26 23:22 UTC, mmartinezintersys commented
💚 TESTED

QA Details: 

 - Verify a request to bigpay is done when the referred flow is triggered

2021-03-01 23:54 UTC, capsula4 approved these changes

2021-03-12 17:59 UTC, roberbnd commented
MERGE ORDER: 
1. [feat(payment): INT-3896 [Zip] getInitializationData indicates if deferred flow experiment is enabled](https://github.com/bigcommerce/bigcommerce/pull/39599) 
2. This PR

2021-03-14 23:14 UTC, merged