feat(payment): INT-4258: StripeV3: Improve error handling
bigcommerce/checkout-sdk-js pull request #1127
Opened 2021-04-30 20:54 UTC by mauricio-sg

## What? [INT-4258](https://jira.bigcommerce.com/browse/INT-4258)
Handle RequestError's `required_field` code in order to show a more descriptive [message](https://stripe.com/docs/api/errors#errors-message) to the shopper instead of the generic one provided by bigpay.

## Why?
To improve UX and error tracing.

## Testing / Proof
WOI

## Sibling PR
https://github.com/bigcommerce/bigpay/pull/3736

@bigcommerce/apex-integrations  @bigcommerce/checkout @bigcommerce/payments

2021-05-03 15:24 UTC, cbandam approved these changes
👍  Looks good to me. Nice refactoring @mauricio-sg.
I'd suggest @clopezh and @vmparra to also take a peek at this PR, please.

2021-05-03 17:51 UTC, vmparra requested changes
Hey @mauricio-sg, so far looks real good. I just left one comment, please tell me if you have any question.

2021-05-03 17:51 UTC, vmparra commented on src/payment/strategies/stripev3/stripev3-payment-strategy.ts
> +            return await this._processAdditionalAction(error, stripeError, methodId, shouldSaveInstrument, shouldSetAsDefaultInstrument);
I personally don't like to keep adding arguments to this function, in fact, `processAdditionalAction` was intended for only for that matter. 

In this case what I would do is just create an `if` block and validate `error`

2021-05-03 21:36 UTC, mauricio-sg commented
@vmparra please ♻️ thanks!

2021-05-03 22:11 UTC, vmparra approved these changes
LGTM 👍🏻

2021-05-03 23:51 UTC, capsula4 approved these changes

2021-05-05 19:19 UTC, JoseBobadilla20 commented
💚 Tested
QA Details: I ran a basic regression for Stripe checking the correct error messages.

2021-05-05 22:48 UTC, merged