INT-4087 Send the client token back to update the payment intent related for StripeV3
bigcommerce/checkout-sdk-js pull request #1164
Opened 2021-06-25 22:12 UTC by BC-AOrtiz

[INT-4087](https://jira.bigcommerce.com/browse/INT-4087)

## What?
- Send back the client token to bigpay to update the related payment intent when place a order using a credit card

## Why?
- Update the payment intent instead to create a new one to prevent to left a incomplete payment intent

## Testing / Proof
...

@bigcommerce/checkout @bigcommerce/payments

2021-06-28 22:34 UTC, vmparra commented
It looks real good. Do you think you can add a few test cases?

2021-06-29 17:00 UTC, BC-AOrtiz commented
♻️ @vmparra I added a test, plese take another look.

2021-06-29 19:22 UTC, vmparra approved these changes
LGTM 👍🏻

2021-06-30 12:19 UTC, icatalina approved these changes

2021-06-30 12:19 UTC, icatalina commented on src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
> +                it('with credit card passing back the client token', async () => {
🍹 I know the rest of the file is written like this, probably a pattern we have in other places, but this line should be "readable". _it with credit card passing back the client token_ makes little to no sense 😅 

I guess we are missing the _what_ in that phrase: _it submits(?) with a credit card and passes back the client token_?

2021-07-08 14:18 UTC, icatalina approved these changes

2021-07-09 19:58 UTC, BC-ISilva commented
💚 Tested!

QE Details:
PR has been validated without issues, Now only 1 order display ones for merchant in Stripe dashboard.
Following scenarios has been validated:
- Auth+Capture.
- AuthOnly.
- Apple Pay.
- Manual Order.
- API orders (with and without vaulted cards).
- Capture.
- Etcetera.

Please review Attached file with validation details.

[INT-4087 - [StripeV3] Duplicate entries in Stripe V3 dashboard.docx](https://github.com/bigcommerce/checkout-sdk-js/files/6793698/INT-4087.-.StripeV3.Duplicate.entries.in.Stripe.V3.dashboard.docx)

2021-07-09 20:03 UTC, vmparra commented on src/payment/strategies/stripev3/stripev3-payment-strategy.ts
> +            if (method === StripeElementType.CreditCard ) {
Please remove entra space before closing parenthesis.

2021-07-09 20:05 UTC, vmparra requested changes
Hi @BC-AOrtiz I left one last comment after reading more carefully.

2021-07-09 22:44 UTC, vmparra approved these changes
LGTM 👍🏻

2021-07-13 01:15 UTC, merged