fix(payment): INT-4661 [Afterpay] get countryCode by shopperCurrency
bigcommerce/checkout-sdk-js pull request #1186
Opened 2021-07-16 21:35 UTC by orecio-bc

## What?
Get the countryCode from the  shopperCurrency instead from the store country, so Afterpay will redirect to the correct portal

## Why?
In the current state, Afterpay gets the countryCode from the storeCounterry, which causes an error while using multicurrency, if the store was in NZ and the shopper was purchasing in CAD or USD, Afterpay would redirect this merchant to the NZ portal, which is not the intended behavior.

## Testing / Proof
https://drive.google.com/file/d/1lJr5NCaFU4HCipKyg7e6QEkOWwYR_85D/view?usp=sharing

@bigcommerce/checkout @bigcommerce/payments @bigcommerce/apex-integrations

2021-07-16 22:14 UTC, HadesDX approved these changes
LGTM

2021-07-19 17:58 UTC, josesonora requested changes

2021-07-19 17:58 UTC, josesonora commented on src/payment/strategies/afterpay/afterpay-payment-strategy.ts
> +        const storeCountryName = this._mapCurrencyToISO2(config?.shopperCurrency.code || '');
```suggestion
        const countryCode = this._mapCurrencyToISO2(config?.shopperCurrency.code || '');
```

2021-07-19 17:58 UTC, josesonora commented on src/payment/strategies/afterpay/afterpay-payment-strategy.ts
> +        const storeCountryName = this._mapCurrencyToISO2(config?.shopperCurrency.code || '');
same here

2021-07-19 17:58 UTC, josesonora commented on src/payment/strategies/afterpay/afterpay-payment-strategy.ts
> +        this._afterpaySdk.initialize({ countryCode: countryName });
change the parameter name to **countryCode**

```suggestion
        this._afterpaySdk.initialize({ countryCode });
```

2021-07-19 18:40 UTC, josesonora approved these changes

2021-07-21 16:03 UTC, orecio-bc commented
@animesh1987 changes ready ♻️

2021-07-22 07:56 UTC, animesh1987 approved these changes

2021-07-22 08:00 UTC, animesh1987 commented on src/payment/strategies/afterpay/afterpay-payment-strategy.ts
> +        return countryByCurrency[currencyCode];
Can we add a check here in the case if currencyCode passed here is `''` or something else other than the specified countries?

2021-07-22 13:49 UTC, orecio-bc commented
@animesh1987 thanks, changes ready ♻️

2021-07-22 14:01 UTC, animesh1987 approved these changes

2021-07-23 21:01 UTC, JuanTorres077 commented
💚 Tested
QA Details: 
After Pay V1 and V2 were tested to support  below currencies:
AUD, CAD, NZD, USD.
Please take a look for further details:
[1186 .pdf](https://github.com/bigcommerce/checkout-sdk-js/files/6871159/1186.pdf)

2021-07-27 08:46 UTC, merged