fix(checkout): INT-5543 [CKO] Update to 3ds on Googlepay
bigcommerce/checkout-sdk-js pull request #1378
Opened 2022-03-17 00:09 UTC by FranciscoOnt

## What?
...

## Why?
...

## Testing / Proof
...

bigcommerce/checkout bigcommerce/payments

2022-03-22 22:02 UTC, JoseAlvarezHdz approved these changes
LGTM 👍🏾

2022-03-23 22:49 UTC, vmparra requested changes
Hi @FranciscoOnt, so far it looks real great, thanks for doing this. I left a comment, please let me know if you have questions.

2022-03-23 22:49 UTC, vmparra commented on src/payment/create-payment-strategy-registry.ts
> +            undefined,
Instead of adding arguments, can we instead implement a common interface that all payment processors can implement?

2022-03-28 19:54 UTC, vmparra approved these changes
LGTM 👍🏻

2022-03-29 08:07 UTC, Tharaae approved these changes
LGTM, only a few minor comments.

2022-03-29 08:07 UTC, Tharaae commented on src/payment/strategies/googlepay/googlepay-payment-strategy.ts
> +        return Promise.reject(error);
💅 
```suggestion
        if (!this._googlePayProviderProcessor) {
            return Promise.reject(error);
        }

        return this._googlePayProviderProcessor.processAdditionalAction(error);
```

2022-03-30 05:04 UTC, animesh1987 commented on src/payment/strategies/googlepay/googlepay-checkoutcom-payment-processor.ts
> +            window.location.replace(redirectUrl);
Does it make sense to use `assign` method here, since `replace` doesn't preserve the session history?

2022-03-30 05:07 UTC, animesh1987 commented on src/payment/strategies/googlepay/googlepay-payment-strategy.ts
> +        private _googlePayProviderProcessor?: GooglePayProviderProcessor,
We are changing adyenProcessor to a more generic one? Does that seem right?

2022-03-30 23:43 UTC, JuanTorres077 commented
💚  Tested

QA Details: 

CHKO with GPay using MC 3ds, Tested and working as expected...

Unfortunately, GPay doesn't have MC 3ds's CC.  We tested with all CCs included in Gpay...

[Evidence](https://drive.google.com/drive/folders/1l3af6yScIVPNG712nfwjo4AsE-0_X0Ue?usp=sharing )

Waiting for Roll out in order to verify everything going well...

2022-03-31 14:37 UTC, vitalii-koshovyi approved these changes
Looks good from Adyen perspective!

2022-04-01 03:41 UTC, animesh1987 approved these changes

2022-04-03 23:59 UTC, merged