fix(payment): INT-5854 [Mollie] Klarna is not available if cart contains digital products
bigcommerce/checkout-sdk-js pull request #1510
Opened 2022-07-19 22:45 UTC by bc-alejandroRodriguez

## What? [INT-5854](https://bigcommercecloud.atlassian.net/browse/INT-5854)
I want to hide any Klarna Pay Later and Klarna Slice It from shoppers if their cart contains digital products

## Why?
So that I can prevent shoppers from trying to pay for an ineligible cart and getting an error

## Testing / Proof

Before
https://user-images.githubusercontent.com/104527753/180102690-63e27651-3e1d-466b-bc3d-24f71aaf2b78.mov

After
https://user-images.githubusercontent.com/104527753/180099759-592b8826-6aea-4258-a53c-4835332259d4.mov

@bigcommerce/checkout @bigcommerce/apex-integrations

2022-07-25 17:15 UTC, vmparra commented on packages/core/src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
> +import {getCart} from "../../../cart/carts.mock";
Just add spaces before and after curly braces 💅🏻

2022-07-25 17:16 UTC, vmparra requested changes
I loved what you did, I just left one comment.

2022-07-25 20:51 UTC, vmparra approved these changes
LGTM 👍🏻

2022-08-05 05:33 UTC, animesh1987 commented on packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
> +            if(cartDigitalItems && cartDigitalItems.length > 0){
```suggestion
            if (cartDigitalItems && cartDigitalItems.length > 0){
```

2022-08-05 05:34 UTC, animesh1987 commented on packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
> +        if(methodsNotAllowedWhenDigitalOrder.includes(methodId)) {
```suggestion
        if (methodsNotAllowedWhenDigitalOrder.includes(methodId)) {
```

2022-08-05 05:35 UTC, animesh1987 commented on packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
> +
```suggestion
            const cart = state.cart.getCartOrThrow();
```

2022-08-12 00:35 UTC, animesh1987 approved these changes

2022-08-12 00:42 UTC, merged

2022-08-15 22:04 UTC, BC-ISilva commented
💚 Tested!

QE Details:
User story has been validated, following scenarios have been tested:

1. If the cart consists solely of one or more digital products and the shopper selects Klarna Pay Later or Klarna Slice It, then the following message will appear within the component and the Place Order button will be grayed out.
2. If the cart is mixed with both digital and physical products and the shopper selects Klarna Pay Later or Klarna Slice It, then the following message will appear within the component and the Place Order button will be grayed out
3. If the shopper applies a coupon code in checkout which adds a digital product after Klarna Pay Later or Klarna Slice It has already appeared as an option, then the shopper will be shown an error
4. Klarna Pay Now does not look at whether there is a digital product or not in the cart.
5. Shoppers select Klarna Pay later or Slice it and then applies a coupon to add digital items as gif.

Please review attached word document with validation details:
[INT-5854 [Mollie] Klarna Is Not Available If Cart Contains Digital Products.docx](https://github.com/bigcommerce/checkout-sdk-js/files/9340088/INT-5854.Mollie.Klarna.Is.Not.Available.If.Cart.Contains.Digital.Products.docx)