fix(payment): STRIPE-130 Stripe UPE making postal code not always required to make purchase
bigcommerce/checkout-sdk-js pull request #1565
Opened 2022-08-15 20:22 UTC by JavvmBC

## What? [STRIPE-130](https://bigcommercecloud.atlassian.net/browse/STRIPE-130)
StripeUPE always requires to get a postal code and in some countries is not needed so i deleted the validation in the _mapStripePaymentData function

## Why?
StripeUPE unable to process payments for billing address where no zip/postal code is required

## Testing / Proof

Before change:
<img width="812" alt="Screen Shot 2022-08-15 at 15 20 27" src="https://user-images.githubusercontent.com/106765049/184711501-4ba781c6-620b-44a1-8817-aff8a02c42be.png">
 
After change:
<img width="827" alt="Screen Shot 2022-08-15 at 15 21 03" src="https://user-images.githubusercontent.com/106765049/184711583-e85dc058-9d49-4ff3-9a8d-d64d041def3d.png">

@bigcommerce/checkout @bigcommerce/payments @bigcommerce/apex-integrations

2022-08-15 21:03 UTC, vmparra requested changes
So far looks good. Please add few test cases.

2022-08-15 21:10 UTC, BC-PabloRivera commented
If i remember correctly there are some APMs that require the postal code to continue, and if you don't map it from the billing you'll have to remove the line 266

2022-08-16 20:45 UTC, JavvmBC commented
> If i remember correctly there are some APMs that require the postal code to continue, and if you don't map it from the billing you'll have to remove the line 266

Changes done, thank you for telling me

2022-08-16 20:45 UTC, JavvmBC commented
> So far looks good. Please add few test cases.

More test cases added

2022-08-22 20:35 UTC, BC-AOrtiz commented
♻️ @vmparra changes have been addressed, please take another look.

2022-08-22 21:39 UTC, vmparra approved these changes
LGTM 👍🏻

2022-08-23 01:20 UTC, animesh1987 approved these changes

2022-08-25 19:43 UTC, BCHMercado commented
💚  Testing Done !
https://bigcommercecloud.atlassian.net/jira/software/c/projects/STRIPE/boards/622?modal=detail&selectedIssue=STRIPE-130

2022-08-29 23:38 UTC, merged