feat(payment): PAYPAL-4123 Update address request body by adding digitalItems to lineItems
bigcommerce/checkout-sdk-js pull request #2504
Opened 2024-05-13 12:04 UTC by bc-nick

## What?

Update address request body by adding digitalItems to lineItems

## Why?

If we try to place order with digital item we get an error by clicking on Pay button in the GP modal window
We need to update request body by adding digitalItems to lineItems to avoid this error

## Testing / Proof

Before

https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/f6056cfc-7f1d-437c-b0af-aa08e848fbd8

After

https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/f45b44de-4340-426f-8042-6367092dcb90

@bigcommerce/team-checkout @bigcommerce/team-payments

2024-05-13 12:28 UTC, bc-dronov approved these changes

2024-05-14 08:51 UTC, richapatel1510 approved these changes
LGTM 👍

2024-05-14 08:51 UTC, animesh1987 requested changes
Hey @bc-nick this might cause issues with regular consignments, since we don't need digital items.

I will suggest we probably need to find another way to fix this.

2024-05-14 10:01 UTC, serhii-tkachenko commented
Yeah... when customer is buying digital item with buy now cart, then we should not use consignment for this case at all

2024-05-14 10:10 UTC, closed without merging