feat(payment): PI-2403 Pay by Bank integration
bigcommerce/checkout-sdk-js pull request #2619
Opened 2024-08-21 11:59 UTC by bc-ania

## What?
Pay By Bank is a supported payment method - [Pay by Bank (Open Banking)](https://developers.bluesnap.com/reference/pay-by-bank)

Allow shoppers to input IBAN in the Pay By Bank payment step

Shopper Experience

Shopper selects Pay By Bank in the Payment Step of BigCommerce checkout

Shopper sees a text input for IBAN. Shopper types in the value

Shopper clicks Place Order and is redirected to authenticate with their bank

Shopper is returned to BigCommerce and arrives at the Order Confirmation page is transaction status is successful (Awaiting Fulfillment) or pending (Awaiting Payment)

If the shopper cancels the transaction, shopper is returned to checkout page

## Why?
To allow shoppers to use Pay by Bank method

## Testing / Proof
...

2024-08-22 10:22 UTC, vitalii-koshovyi commented on packages/bluesnap-direct-integration/src/utils/is-bluesnap-direct-instrument.ts
> +        typeof paymentData === 'object' && paymentData !== null && 'iban' in paymentData,
I would add an additional check that paymentData doesn't have firstName, lastName, shopperPermission to avoid
collision with Sepa Instrument

2024-08-26 12:43 UTC, bc-nick approved these changes

2024-08-27 11:38 UTC, vitalii-koshovyi requested changes
please add e2e test

2024-08-27 11:40 UTC, vitalii-koshovyi approved these changes

2024-08-28 04:41 UTC, merged