feat(payment): STRIPE-473 stripe test files types updated
bigcommerce/checkout-sdk-js pull request #2692
Opened 2024-10-09 16:51 UTC by bc-dronov

## What?
...

## Why?
...

## Testing / Proof
...

@bigcommerce/team-checkout @bigcommerce/team-payments

2024-10-10 22:01 UTC, bc-peng approved these changes

2024-10-10 22:34 UTC, animesh1987 approved these changes

2024-10-11 08:14 UTC, vitalii-koshovyi requested changes
Please fix "Cannot log after tests are done." errors

2024-10-11 08:34 UTC, bc-dronov commented
> Please fix "Cannot log after tests are done." errors

Done

2024-10-11 08:37 UTC, vitalii-koshovyi approved these changes
Well done!

2024-10-11 08:52 UTC, merged