Int 3001
bigcommerce/checkout-sdk-js pull request #967
Opened 2020-08-26 17:55 UTC by christianahvilla

## What?
...

## Why?
...

## Testing / Proof
...

@bigcommerce/checkout @bigcommerce/payments

2020-09-02 23:37 UTC, mauricio-sg requested changes
Looking good so far, just a few more small changes 😁

2020-09-02 23:37 UTC, mauricio-sg commented on src/payment/strategies/converge/converge-payment-strategy.spec.ts
> +            orderRequestBody = { ...orderRequestBody, payment: {...orderRequestBody.payment, methodId: 'authorizenet' } };
I insist this is not necessary. Why are you sending `authorizenet`? 🤔

2020-09-02 23:37 UTC, mauricio-sg commented on src/payment/strategies/converge/converge-payment-strategy.spec.ts
> +        it('does not load converge if initialization options are not provided', async () => {
Why did you change the name? 🤔 it was right but, it should say `if 3ds is not required`.

2020-09-03 17:59 UTC, mauricio-sg approved these changes
LGTM 👍

2020-09-08 15:42 UTC, christianahvilla commented
Elavon would like us to pivot to adding new capabilities onto the existing Sage Pay Direct.

2020-09-08 15:42 UTC, closed without merging